-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alerts
(
    id_recordatorio integer NOT NULL DEFAULT nextval('recordatorios_id_recordatorio_seq'::regclass),
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha_recordatorio timestamp without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    dias_anticipacion integer DEFAULT 0,
    recurrencia character varying(20) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    prioridad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT recordatorios_pkey PRIMARY KEY (id_recordatorio)
);

CREATE TABLE IF NOT EXISTS public.appointments
(
    id_cita serial NOT NULL,
    id_cliente integer,
    id_empleado integer,
    id_servicio integer,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    notas text COLLATE pg_catalog."default",
    recordatorio_enviado boolean DEFAULT false,
    CONSTRAINT appointments_pkey PRIMARY KEY (id_cita)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id_cliente serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default",
    documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    codigo_postal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default",
    pais character varying(100) COLLATE pg_catalog."default" DEFAULT 'España'::character varying,
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    razon_social character varying(200) COLLATE pg_catalog."default",
    regimen_fiscal character varying(50) COLLATE pg_catalog."default",
    descuento_preferencial numeric(5, 2) DEFAULT 0,
    notas text COLLATE pg_catalog."default",
    fecha_registro date DEFAULT CURRENT_DATE,
    fecha_ultima_compra date,
    tipo_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipo_documento character varying(10) COLLATE pg_catalog."default" NOT NULL,
    provincia character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tipo_iva character varying(20) COLLATE pg_catalog."default" DEFAULT 'general'::character varying,
    CONSTRAINT clients_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT clients_documento_key UNIQUE (documento)
);

CREATE TABLE IF NOT EXISTS public.employee_services
(
    id_empleado_servicio serial NOT NULL,
    id_empleado integer,
    id_servicio integer,
    porcentaje_comision numeric(5, 2),
    CONSTRAINT employee_services_pkey PRIMARY KEY (id_empleado_servicio),
    CONSTRAINT employee_services_id_empleado_id_servicio_key UNIQUE (id_empleado, id_servicio)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id_empleado integer NOT NULL DEFAULT nextval('empleados_id_empleado_seq'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dni character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    fecha_contratacion date NOT NULL,
    cargo character varying(50) COLLATE pg_catalog."default",
    salario numeric(10, 2),
    activo boolean DEFAULT true,
    documento_adjunto text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    nss character varying(20) COLLATE pg_catalog."default",
    telefono_emergencia character varying(20) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    codigo_postal character varying(10) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default",
    pais character varying(100) COLLATE pg_catalog."default" DEFAULT 'España'::character varying,
    fecha_nacimiento date,
    horas_contratadas integer NOT NULL DEFAULT 40,
    tipo_contrato character varying(50) COLLATE pg_catalog."default",
    notas text COLLATE pg_catalog."default",
    departamento character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT empleados_pkey PRIMARY KEY (id_empleado),
    CONSTRAINT empleados_dni_key UNIQUE (dni),
    CONSTRAINT empleados_email_key UNIQUE (email),
    CONSTRAINT employees_nss_key UNIQUE (nss)
);

CREATE TABLE IF NOT EXISTS public.expenses
(
    id_gasto integer NOT NULL DEFAULT nextval('gastos_id_gasto_seq'::regclass),
    tipo_gasto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    concepto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    monto numeric(10, 2) NOT NULL,
    fecha_gasto date DEFAULT CURRENT_DATE,
    comentarios text COLLATE pg_catalog."default",
    CONSTRAINT gastos_pkey PRIMARY KEY (id_gasto)
);

CREATE TABLE IF NOT EXISTS public.income
(
    id_ingreso integer NOT NULL DEFAULT nextval('ingresos_id_ingreso_seq'::regclass),
    fecha_ingreso date DEFAULT CURRENT_DATE,
    ingresos numeric(10, 2) NOT NULL,
    comentarios text COLLATE pg_catalog."default",
    concepto character varying(100) COLLATE pg_catalog."default",
    categoria character varying(100) COLLATE pg_catalog."default",
    metodo_ingreso character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT ingresos_pkey PRIMARY KEY (id_ingreso)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id_producto integer NOT NULL DEFAULT nextval('inventarios_id_producto_seq'::regclass),
    nombre_producto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    cantidad_actual integer NOT NULL,
    cantidad_minima integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    id_proveedor integer,
    fecha_actualizacion date DEFAULT CURRENT_DATE,
    referencia character varying(50) COLLATE pg_catalog."default",
    pvp numeric(10, 2) DEFAULT 0.00,
    CONSTRAINT inventarios_pkey PRIMARY KEY (id_producto),
    CONSTRAINT inventory_referencia_key UNIQUE (referencia)
);

CREATE TABLE IF NOT EXISTS public.leaves
(
    id_baja integer NOT NULL DEFAULT nextval('bajas_id_baja_seq'::regclass),
    id_empleado integer,
    tipo_baja character varying(50) COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    comentarios text COLLATE pg_catalog."default",
    CONSTRAINT bajas_pkey PRIMARY KEY (id_baja)
);

CREATE TABLE IF NOT EXISTS public.order_detail
(
    id_detalle serial NOT NULL,
    id_pedido integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) GENERATED ALWAYS AS (((cantidad)::numeric * precio_unitario)) STORED,
    CONSTRAINT order_detail_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id_pedido serial NOT NULL,
    id_proveedor integer NOT NULL,
    id_gasto integer,
    fecha_pedido timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_entrega_estimada timestamp without time zone,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    total numeric(10, 2),
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    comentarios text COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.product_codes
(
    id_codigo serial NOT NULL,
    id_producto integer,
    codigo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tipo_codigo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion date DEFAULT CURRENT_DATE,
    CONSTRAINT product_codes_pkey PRIMARY KEY (id_codigo),
    CONSTRAINT product_codes_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.sale_products
(
    id_detalle_producto serial NOT NULL,
    id_venta integer,
    id_producto integer,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    porcentaje_descuento numeric(5, 2) DEFAULT 0,
    porcentaje_impuesto numeric(5, 2) DEFAULT 0,
    subtotal numeric(10, 2) NOT NULL,
    CONSTRAINT sale_products_pkey PRIMARY KEY (id_detalle_producto)
);

CREATE TABLE IF NOT EXISTS public.sale_services
(
    id_detalle_servicio serial NOT NULL,
    id_venta integer,
    id_servicio integer,
    id_empleado integer,
    horas_trabajadas numeric(6, 2),
    id_nivel_servicio integer,
    cantidad integer DEFAULT 1,
    precio_unitario numeric(10, 2) NOT NULL,
    porcentaje_descuento numeric(5, 2) DEFAULT 0,
    porcentaje_impuesto numeric(5, 2) DEFAULT 0,
    fecha_programada timestamp without time zone,
    fecha_completado timestamp without time zone,
    estado_servicio character varying(20) COLLATE pg_catalog."default" DEFAULT 'completado'::character varying,
    subtotal numeric(10, 2) NOT NULL,
    notas_servicio text COLLATE pg_catalog."default",
    CONSTRAINT sale_services_pkey PRIMARY KEY (id_detalle_servicio)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id_venta serial NOT NULL,
    numero_documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipo_documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_emision timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_cliente integer,
    id_empleado_vendedor integer,
    subtotal numeric(10, 2) NOT NULL,
    descuento numeric(10, 2) DEFAULT 0,
    impuestos numeric(10, 2) DEFAULT 0,
    total numeric(10, 2) NOT NULL,
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    notas text COLLATE pg_catalog."default",
    venta_relacionada integer,
    id_usuario_registro integer,
    tipo_iva character varying(20) COLLATE pg_catalog."default",
    porcentaje_iva numeric(5, 2) DEFAULT 21.00,
    porcentaje_retencion numeric(5, 2) DEFAULT 0,
    CONSTRAINT sales_pkey PRIMARY KEY (id_venta),
    CONSTRAINT sales_numero_documento_key UNIQUE (numero_documento)
);

CREATE TABLE IF NOT EXISTS public.service_levels
(
    id_nivel serial NOT NULL,
    id_servicio integer,
    nombre_nivel character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio numeric(10, 2) NOT NULL,
    tiempo_estimado_minutos integer,
    CONSTRAINT service_levels_pkey PRIMARY KEY (id_nivel)
);

CREATE TABLE IF NOT EXISTS public.services
(
    id_servicio serial NOT NULL,
    nombre_servicio character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio_base numeric(10, 2),
    tipo_tarifa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    duracion_estimada_minutos integer,
    categoria character varying(50) COLLATE pg_catalog."default",
    requiere_profesional boolean DEFAULT true,
    activo boolean DEFAULT true,
    fecha_creacion date DEFAULT CURRENT_DATE,
    CONSTRAINT services_pkey PRIMARY KEY (id_servicio)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    id_ajuste integer NOT NULL DEFAULT nextval('ajustes_id_ajuste_seq'::regclass),
    nombre_local character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    url_backend character varying(255) COLLATE pg_catalog."default",
    horario_apertura time without time zone,
    horario_cierre time without time zone,
    logo_local text COLLATE pg_catalog."default",
    tema character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT ajustes_pkey PRIMARY KEY (id_ajuste)
);

CREATE TABLE IF NOT EXISTS public.shift_intervals
(
    id_intervalo serial NOT NULL,
    id_horario integer,
    dia_semana integer,
    hora_entrada time without time zone,
    hora_salida time without time zone,
    CONSTRAINT shift_intervals_pkey PRIMARY KEY (id_intervalo),
    CONSTRAINT unique_shift_interval UNIQUE (id_horario, dia_semana, hora_entrada)
);

CREATE TABLE IF NOT EXISTS public.shifts
(
    id_horario integer NOT NULL DEFAULT nextval('horarios_id_horario_seq'::regclass),
    id_empleado integer,
    fecha_inicio_semana date NOT NULL,
    CONSTRAINT horarios_pkey PRIMARY KEY (id_horario)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    id_proveedor integer NOT NULL DEFAULT nextval('proveedores_id_proveedor_seq'::regclass),
    nombre_proveedor character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contacto character varying(100) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    plantilla_email text COLLATE pg_catalog."default",
    direccion_fiscal character varying(255) COLLATE pg_catalog."default",
    cif character varying(13) COLLATE pg_catalog."default" NOT NULL,
    condiciones_pago character varying(50) COLLATE pg_catalog."default",
    dias_credito integer,
    cuenta_bancaria character varying(20) COLLATE pg_catalog."default",
    moneda character varying(3) COLLATE pg_catalog."default" DEFAULT 'EUR'::character varying,
    sitio_web character varying(100) COLLATE pg_catalog."default",
    fecha_registro date DEFAULT CURRENT_DATE,
    activo boolean DEFAULT true,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id_proveedor)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_usuario integer NOT NULL DEFAULT nextval('usuarios_id_usuario_seq'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_registro date DEFAULT CURRENT_DATE,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.clients (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.services (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_services
    ADD CONSTRAINT employee_services_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.employee_services
    ADD CONSTRAINT employee_services_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.services (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT inventarios_id_proveedor_fkey FOREIGN KEY (id_proveedor)
    REFERENCES public.suppliers (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.leaves
    ADD CONSTRAINT bajas_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_detail
    ADD CONSTRAINT fk_pedido FOREIGN KEY (id_pedido)
    REFERENCES public.orders (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_detail
    ADD CONSTRAINT fk_producto FOREIGN KEY (id_producto)
    REFERENCES public.inventory (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_gasto FOREIGN KEY (id_gasto)
    REFERENCES public.expenses (id_gasto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_proveedor FOREIGN KEY (id_proveedor)
    REFERENCES public.suppliers (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_codes
    ADD CONSTRAINT product_codes_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.inventory (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sale_products
    ADD CONSTRAINT sale_products_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.inventory (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_products
    ADD CONSTRAINT sale_products_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.sales (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sale_services
    ADD CONSTRAINT sale_services_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_services
    ADD CONSTRAINT sale_services_id_nivel_servicio_fkey FOREIGN KEY (id_nivel_servicio)
    REFERENCES public.service_levels (id_nivel) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_services
    ADD CONSTRAINT sale_services_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.services (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_services
    ADD CONSTRAINT sale_services_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.sales (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.clients (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_id_empleado_vendedor_fkey FOREIGN KEY (id_empleado_vendedor)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_id_usuario_registro_fkey FOREIGN KEY (id_usuario_registro)
    REFERENCES public.users (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_venta_relacionada_fkey FOREIGN KEY (venta_relacionada)
    REFERENCES public.sales (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_levels
    ADD CONSTRAINT service_levels_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.services (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.shift_intervals
    ADD CONSTRAINT shift_intervals_id_horario_fkey FOREIGN KEY (id_horario)
    REFERENCES public.shifts (id_horario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.shifts
    ADD CONSTRAINT horarios_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.employees (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;